export const SET_EMAIL = "SET_EMAIL";
export const SET_FREEBOOKS = "SET_FREEBOOKS";
export const SET_PAIDBOOKS = "SET_PAIDBOOKS";
export const SET_BOUGHTBOOKS = "SET_BOUGHTBOOKS";
export const SET_CHECKEDOUTBOOKS = "SET_CHECKEDOUTBOOKS";
export const SET_CART = "SET_CART";