export * as register from './register'
export * as authenticateEmail from './authenticateEmail'
export * as resendEmail from './resendEmail'
export * as login from './login'
export * as loginWithFacebook from './loginWithFacebook'
export * as recoverPassword from './recoverPassword'
export * as checkPasswordToken from './checkPasswordToken'
export * as changePassword from './changePassword'
