export { detectMobileDevice } from './detectMobileDevice'
export { handleApiError } from './handleApiError'
export * from './loader'
export { setApiFeedback } from './setApiFeedback'
export { setLoading } from './setLoading'
export { subscribePushNotifications } from './subscribePushNotifications'
