export { detectMobileDevice } from './detectMobileDevice.web'
export { handleApiError } from './handleApiError'
export { isChatInitialLoad } from './isChatInitialLoad'
export { debounceLoader, resetLoader } from './loader'
export { setApiFeedback } from './setApiFeedback'
export { setLoading } from './setLoading'
export { setRole } from './setRole'
export { subscribePushNotifications } from './subscribePushNotifications.web'
